-- auto-generated definition
create table customers
(
    id       bigint generated by default as identity
        constraint customers_pkey
            primary key,
    email    varchar(128),
    fullname varchar(128),
    name     varchar(128),
    password varchar(128)
);

alter table customers
    owner to postgres;



insert into places_table (name, address, image)
values ('Gadget', 'SUM G-50', '');

